### ISSUE TITLE
About visualization

### ISSUE THREAD

**Issue by shuowang666** [astra-vision/MonoScene#43]
Hello, I followed your visualization code, but I found that the visualization results seemed different from what you showed. What should I do to get the results you displayed on your home page?
![image](https://user-images.githubusercontent.com/56186807/210694481-3e256594-5514-44d0-b021-f872943b0afd.png)

**Comment by anhquancao** [comment]
The results look really weird. You can take a look at the demo on huggingface
https://huggingface.co/spaces/CVPR/MonoScene

**Comment by shuowang666** [comment]
Thanks for your answering! 
I look at the demo on huggingface, and I find that the results do differ a little bit from what I got. I want to know whether the visualization on the Huggingface is produced by monoscene/scripts/on the visualization/kitti_vis_pred.py?
![image](https://user-images.githubusercontent.com/56186807/210776111-90e4cc35-96a5-420d-9f0c-887ff5beccbf.png)

What is more, if I want to get the results that your home page show below, how should I modify the code?
![image](https://user-images.githubusercontent.com/56186807/210776334-e0e53900-f351-4512-8584-18520595b9b0.png)

**Comment by anhquancao** [comment]
It's different because of the plotting library only. The technique is the same: I convert the voxels to points and plot them with the color and with square shape (on my homepage) and circle (huggingface). 
I think the problem is not the plotting in your cases. The output results seem weird, I never see the car class (blue color) with that shape. Could you double check the output?

**Comment by shuowang666** [comment]
I will check my output again. Thank you.
