### ISSUE TITLE
Coordinate in SSC

### ISSUE THREAD

**Issue by apollo7747** [astra-vision/MonoScene#63]
Hi, thank you for your great work.

I am new to this field, and I have the following questions when reading your code:

1. I find that the GT of SSC is generated by data/semantic_kitti/preprocess.py. I am curious about which coordinates the GT is in. I did not find the coordinate transformation of voxel in your code. Does this mean that this gt is in the camera coordinate? Or do you implicitly complete the coordinate transformation through the network directly with the image?

2. In data/semantic_kitti/preprocess.py, I find that  self.vox_origin = np.array([0, -25.6, -2]). How to get this, I didn't find the relevant numbers in SemanticKITTI.

Looking forward to your reply, thanks again for the great work

**Comment by anhquancao** [comment]
Hi @apollo7747 ,
1. The GT of SSC for semantic kitti is in the lidar cooridnate.
2. You can take a look at Sec. 5, data generation in the paper https://arxiv.org/pdf/1904.01416.pdf 
Since they took the volumn of 51.2 m ahead of the car, 25.6 m to every side and 6.4 m in height, the voxel origin is the starting point of the volume which is 0m, -25.6m, -2m in the x, y, z axes of the lidar coordinate. 
The data generation code is here
https://github.com/jbehley/voxelizer
The setting is also shown in the image in the repo
![image](https://github.com/astra-vision/MonoScene/assets/9668858/7d65e9d9-b9d6-4af3-91ec-269e16fe658f)

**Comment by anhquancao** [comment]
Yes, the current implementation outputs directly in the lidar coordinates. This eases the evaluation since the GT is voxelized and converting back and forth could slightly alter the GT due to discretization.

**Comment by apollo7747** [comment]
You cleared up all my confusion which helped me a lot. Thanks again!

**Comment by anhquancao** [comment]
Awesome, I'm glad that it helps.
