### ISSUE TITLE
vox2pix

### ISSUE THREAD

**Issue by yty-sky** [astra-vision/MonoScene#65]
The vox2pix code is that:
 projected_pix, fov_mask, pix_z = vox2pix(
                T_velo_2_cam,
                cam_k,
                self.vox_origin,
                self.voxel_size * scale_3d,
                self.img_W,
                self.img_H,
                self.scene_size,
            )            
This operation will project the voxel to the 0th camera, not 2nd camera, Is there a mistake?

**Comment by anhquancao** [comment]
Hi @yty-sky, you are correct. It is a mistake. I tried to change to the 2nd camera and retrained but nothing change.
I think it is due to the fact that the two cameras are parallel and very close two each other. 
Also, we unproject the extracted feature with large receptive field, thus it also cover the correct pixels.

**Comment by yty-sky** [comment]
> Hi @yty-sky, you are correct. It is a mistake. I tried to change to the 2nd camera and retrained but nothing change. I think it is due to the fact that the two cameras are parallel and very close two each other. Also, we unproject the extracted feature with large receptive field, thus it also cover the correct pixels.

Yes, it is. Thank you for your reply
